services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env
    environment:
      - MYSQL_USER=${USERNAME}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_USER=${USERNAME}
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
    
  api:
    build:
      context: .
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - database
    restart: on-failure
    develop:
      watch:
        - action: sync
          path: ./usr/src/app
          target: ./usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

    ports:
      - "3001:3001"

volumes:
  db_data: