services:
  happye_db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file: .env
    environment:
      - MYSQL_USER=${USERNAME}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_USER=${USERNAME}
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
    
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}
      HOST: ${HOST}
      DATABASE: ${DATABASE}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      DBPORT: ${DBPORT}
      APPLICATION_PORT: ${APPLICATION_PORT}
      
    depends_on:
      - happye_db
    restart: on-failure
    develop:
      watch:
        - action: sync
          path: ./
          target: ./usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

    ports:
      - "3000:3000"

volumes:
  db_data: